databases:
  - name: demo-postgres
    plan: free

services:
  # BACKEND (Express)
  - type: web
    name: simple-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: "npm ci || npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: demo-postgres
          property: connectionString
      # ⚠️ Ở bước đầu deploy bạn CHƯA BIẾT URL frontend,
      # nên tạm để CORS mở toàn bộ, sau khi deploy xong thì update lại:
      - key: ALLOW_ORIGIN
        value: "*"

  # FRONTEND (Static Site)
  - type: web
    name: simple-frontend
    runtime: static
    rootDir: client
    staticPublishPath: .
    envVars:
      # ⚠️ Ở lần đầu, bạn chưa biết URL backend => tạm để giá trị rỗng.
      # Sau khi Render tạo URL backend (vd: https://simple-backend.onrender.com),
      # bạn quay lại và sửa giá trị này trong Render dashboard.
      - key: API_BASE
        value: ""
