databases:
  - name: demo-postgres
    plan: free

services:
  # BACKEND (Express)
  - type: web
    name: simple-backend
    runtime: node
    plan: free
    rootDir: server # backend nằm trong thư mục server/
    buildCommand: "npm ci || npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: demo-postgres
          property: connectionString
      - key: ALLOW_ORIGIN
        value: https://simple-frontend.onrender.com

  # FRONTEND (Static Site)
  - type: web
    name: simple-frontend
    runtime: static
    rootDir: client
    # Tạo file config.js tại build-time, ghi giá trị từ env API_BASE
    buildCommand: bash -lc 'echo "window.API_BASE='\''${API_BASE}'\'';" > config.js'
    staticPublishPath: .
    envVars:
      - key: API_BASE
        value: https://simple-backend-d8e5.onrender.com/api
