databases:
  - name: postgre
    plan: free

services:
  # BACKEND (Express)
  - type: web
    name: backend
    runtime: node
    plan: free
    rootDir: server # backend nằm trong thư mục server/
    buildCommand: "npm ci || npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        value: "https://frontend.onrender.com/api"
        fromDatabase:
          name: postgre
          property: connectionString

  # FRONTEND (Static Site)
  - type: web
    name: frontend
    runtime: static
    rootDir: client
    staticPublishPath: .
    envVars:
      - key: API_BASE
        value: "https://backend.onrender.com/api"
