databases:
  - name: demo-postgres
    plan: free

services:
  # BACKEND (Express)
  - type: web
    name: simple-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: "npm ci || npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: demo-postgres
          # nếu backend và DB cùng Render, ưu tiên đường nội bộ:
          property: internalConnectionString # (nếu chưa có, dùng connectionString)
      - key: ALLOW_ORIGIN
        fromService:
          name: simple-frontend
          type: web
          property: url

    # FRONTEND (Static Site)
  - type: web
    name: simple-frontend
    runtime: static
    rootDir: client
    staticPublishPath: .
    envVars:
      - key: API_BASE
        fromService:
          name: simple-backend
          type: web
          property: url
