databases:
  - name: demo-postgres
    plan: free

services:
  # BACKEND (Express)
  - type: web
    name: backend
    runtime: node
    plan: free
    rootDir: server # backend nằm trong thư mục server/
    buildCommand: "npm ci || npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: ALLOW_ORIGIN
        value: https://frontend-hlo6.onrender.com

  # FRONTEND (Static Site)
  - type: web
    name: frontend
    runtime: static
    rootDir: client
    staticPublishPath: .
