databases:
  - name: demo-postgres
    plan: free

services:
  # BACKEND (Express)
  - type: web
    name: simple-backend
    runtime: node # thay vì env: node
    plan: free
    rootDir: server
    buildCommand: "npm ci"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: demo-postgres
          property: connectionString
      - key: ALLOW_ORIGIN
        value: https://simple-frontend.onrender.com

  # FRONTEND (Static Site)
  - type: web
    name: simple-frontend
    runtime: static # đây là static site
    # Nếu chỉ là HTML/JS thuần trong thư mục client/, KHÔNG build:
    staticPublishPath: ./client
    # Nếu dùng build tool (Vite/React): bật 2 dòng dưới,
    # buildCommand: "npm ci && npm run build"
    # staticPublishPath: ./client/dist
    envVars:
      - key: API_BASE
        value: https://simple-backend.onrender.com/api
